"""initial schema

Revision ID: 870bddd482ac
Revises: 
Create Date: 2026-04-14 01:42:34.903118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '870bddd482ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pin_likes_id'), 'pin_likes', ['id'], unique=False)
    op.drop_index(op.f('ix_pin_lakes_id'), table_name='pin_lakes')
    op.drop_table('pin_lakes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_lakes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], name=op.f('pin_lakes_pin_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.id'], name=op.f('pin_lakes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pin_lakes_pkey'))
    )
    op.create_index(op.f('ix_pin_lakes_id'), 'pin_lakes', ['id'], unique=False)
    op.drop_index(op.f('ix_pin_likes_id'), table_name='pin_likes')
    op.drop_table('pin_likes')
    # ### end Alembic commands ###
